### ISSUE TITLE
myanglog api - CRUD 구현

### ISSUE THREAD

**Issue by myangw** [kiworkshop/community#26]
### myanglog-api 기능 전체

1. 일반적인 CRUD
2. 좋아요 기능 - 나중에 best를 메인에 올린다던지 할 수 있도록
3. 사진 올리기
4. 태그를 등록 가능
5. 검색기능 (나중에 추가하는걸로)

--> 컨셉트는 [브런치](brunch.co.kr) 참고

**Comment by myeongjae-kim** [comment]
이슈 하나에 담기는 코드 양이 많을 것 같아서, 프로젝트를 생성한 뒤 이슈를 여러개로 쪼개서 프로젝트에 등록하면 어떨까요~~

**Comment by myangw** [comment]
아 이중에서 CRUD만 한다는거엿는데 ㅋㅋㅋ CRUD도 따로하는게 좋긴 하겠네요! 의견 반영하겠습니다 ㅎㅎ
